const data = [
  {
    id: "1",
    postal_code: "91789",
    src: "https://media.cnn.com/api/v1/images/stellar/prod/radrunner-beauty-shot-ioaded.jpg?c=16x9&q=h_270,w_480,c_fill",
    catagories: "Fitness",
    description: "Functional one-year-old bike",
    status: "available",
    price: 15,
    email: "abc@gmail.com",
  },
  {
    id: "2",
    postal_code: "92111",
    src: "https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png",
    catagories: "Others",
    description: "This",
    status: "available",
    price: 20,
    email: "abbc@gmail.com",
  },
  {
    id: "3",
    postal_code: "92111",
    src: "https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=350",
    catagories: "Others",
    description: "This is good",
    status: "available",
    price: 100,
    email: "abbcd@gmail.com",
  },
  {
    id: "4",
    postal_code: "92111",
    src: "https://res.cloudinary.com/stealthman22/image/upload/v1586308023/new-portfolio/hero/two-cargo-ships-sailing-near-city-2144905.jpg",
    catagories: "Others",
    description: "This is the description4",
    status: "available",
    price: 100,
    email: "abbcd@gmail.com",
  },
  {
    id: "4",
    postal_code: "92111",
    src: "https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png",
    catagories: "Others",
    description: "This is the description5",
    status: "available",
    price: 100,
    email: "bcd@gmail.com",
  },
  {
    id: "5",
    postal_code: "92117",
    src: "https://www.mensjournal.com/wp-content/uploads/2021/03/miyabi-3.jpg?w=1600&quality=86&strip=all",
    catagories: "Kitchenware",
    description:
      "Japanese knife dsfsdafdsfdsfdsafdsfdsfsdafdsafdsafdsasedfsdfdsfdsfdsfwefwerwerewrwerwerewrewrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    status: "available",
    price: 15,
    email: "cba@gmail.com",
  },
  {
    id: "6",
    postal_code: "92117",
    src: "https://www.mensjournal.com/wp-content/uploads/2021/03/miyabi-3.jpg?w=1600&quality=86&strip=all",
    catagories: "Kitchenware",
    description:
      "Japanese knife dsfsdafdsfdsfdsafdsfdsfsdafdsafdsafdsasedfsdfdsfdsfdsfwefwerwerewrwerwerewrewrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    status: "available",
    price: 15,
    email: "cba@gmail.com",
  },
];

export default data;
